apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: job 
spec:
  schedule: "*/5 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: job
            image: busybox
            imagePullPolicy: IfNotPresent
            command:
            - /bin/sh
            - -c
            - time wget --post-data 'param=dummy' http://updater:8082/urlupdate_batch/1/arriving
          restartPolicy: OnFailure
