version: 2.1
jobs:
  build:
    docker: 
      - image: circleci/python:3.6.4
        auth:
          username: $DOCKERHUB_USER
          password: $DOCKERHUB_PASSWORD
    steps:
      - checkout
      - run: make k8s-run
