version: 2.1

workflows:
  build-and-deploy:
    docker:
      - image: circleci/python:3.6.4
        auth:
          username: $DOCKERHUB_USER
          password: $DOCKERHUB_PASSWORD
    jobs:
      steps:
        - checkout
        - run: make k8s-run
