version: 2.1

orbs:
  kubernetes: circleci/kubernetes@0.11.2

jobs:
  build:
    docker: 
      - image: circleci/python:3.6.4
        auth:
          username: $DOCKERHUB_USER
          password: $DOCKERHUB_PASSWORD
    steps:
      - checkout
      - kubernetes/install-kubectl
      - run: curl -L https://github.com/kubernetes-incubator/kompose/releases/download/v0.7.0/kompose-linux-amd64 -o kompose && chmod +x kompose && sudo mv ./kompose /usr/local/bin/kompose
      - run: make k8s-run
