version: 2.1

orbs:
  kubernetes: circleci/kubernetes@0.11.2

jobs:
  build:
    docker: 
      - image: circleci/python:3.6.4
        auth:
          username: $DOCKERHUB_USER
          password: $DOCKERHUB_PASSWORD
    steps:
      - checkout
      - kubernetes/install-kubectl
      - run: curl -L https://github.com/kubernetes/kompose/releases/download/v1.22.0/kompose-linux-amd64 -o kompose && chmod +x kompose && sudo mv ./kompose /usr/local/bin/kompose
      - run: make k8s-file
      - kubernetes/install-kubeconfig:
          kubeconfig: KUBECONFIG_DATA
      - kubernetes/create-or-update-resource:
          get-rollout-status: true
          show-kubectl-command: true
          namespace: urllookup
          resource-file-path: /tmp/k8s-tmp.yaml
          resource-name: deployment/urllookup
